---
# CC, default assumes bosh-lite is used
cc_endpoint: http://api.bosh-lite.com
# UAA
uaa_client:
  client_id: cf
  username: "p1-rabbit"
  password: "p1-rabbit-pwd"
service:
  # credentials CC uses to authenticate with the broker
  username: "p1-rabbit"
  password: "367@8G24#e:3pTVwD.ng,YMJKds9<X"
  url: http://10.244.9.14:4567
logging:
  level: debug
  print_stack_traces: true
rabbitmq:
  operator_set_policy:
    enabled: true
    policy_name: "operator_set_policy"
    policy_definition: "{\"ha-mode\":\"exactly\",\"ha-params\":2,\"ha-sync-mode\":\"automatic\"}"
    policy_priority: 50
  management_domain: pivotal-rabbitmq.bosh-lite.com
  hosts:
    - 10.244.9.50
  administrator:
    username: guest
    password: guest
