---
# CC, default assumes bosh-lite is used
cc_endpoint: http://api.bosh-lite.com
service:
  # credentials CC uses to authenticate with the broker
  username: "p1-rabbit"
  password: "367@8G24#e:3pTVwD.ng,YMJKds9<X"
  url: http://10.244.9.14:4567
  name: "p-rabbitmq"
  uuid: 00000000-0000-0000-0000-000000000000
  display_name: "WhiteRabbitMQ"
  plan_uuid: 11111111-1111-1111-1111-111111111111
  offering_description: "this is a long description"
  icon_image: base64_encoded_png
  long_description: "this is a long description"
  provider_display_name: SomeCompany
  documentation_url: https://example.com
  support_url: https://support.example.com
logging:
  level: debug
  print_stack_traces: true
rabbitmq:
  operator_set_policy:
    enabled: true
    policy_name: "operator_set_policy"
    policy_definition: "{\"ha-mode\":\"exactly\",\"ha-params\":2,\"ha-sync-mode\":\"automatic\"}"
    policy_priority: 50
  management_domain: pivotal-rabbitmq.bosh-lite.com
  hosts:
    - 10.244.9.50
  administrator:
    username: guest
    password: guest
